### ISSUE TITLE
tests: провести тест производительности

### ISSUE THREAD

**Issue by scffs** [Diary-SPO/bun-elysia#8]
Скрины и данные залить комментом к этому issue

Тестировать можно через:

1. Apache Benchmark (ab)
[https://httpd.apache.org/docs/2.4/programs/ab.html](https://vk.com/away.php?to=https%3A%2F%2Fhttpd.apache.org%2Fdocs%2F2.4%2Fprograms%2Fab.html&cc_key=)
ab -n 1000 -c 10 http://localhost:3000/

2. Siege
[https://github.com/JoeDog/siege](https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2FJoeDog%2Fsiege&cc_key=)
siege -c 10 -t 60s http://localhost:3000/

3. wrk
[https://github.com/wg/wrk](https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2Fwg%2Fwrk&cc_key=)
wrk -t12 -c400 -d30s http://localhost:3000/

### Команды могут отличаться от действительности, скорость / частоту запросов надо сделать одинаковой

**Comment by Kopchan** [comment]
1. Apache Benchmark (ab)
go: 
```bash
ab -n 1000 -c 10 -H "secret: …" http://192.168.1.16:3002/lessons/298/2023-10-09/2023-10-15 
```
![image](https://github.com/Diary-SPO/bun-elysia/assets/83940856/09a048d8-60d2-40c7-9a1f-1fd7903b8bf2)
bun-elysia:
```bash
ab -n 1000 -c 10 -H "secret: …" http://192.168.1.16:3003/lessons/298/2023-10-09/2023-10-15 
```
![image](https://github.com/Diary-SPO/bun-elysia/assets/83940856/64fc294e-ad5c-4a99-a68c-446460c0a948)

**Comment by scffs** [comment]
Вопросики
1. Точно ли серваки в одинаковых условиях?
2. Может сделаешь тестов 5 и обединишь в одну таблицу?
3. Давай также протестим на других бенчмарках из списка

**Comment by scffs** [comment]
Elysia win see https://github.com/Diary-SPO/service/issues/91
